# Generated by Django 5.0 on 2024-10-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Filial'},
        ),
        migrations.RemoveField(
            model_name='controle',
            name='brand',
        ),
    ]
