# Generated by Django 5.0 on 2024-10-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_branch_options_remove_controle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory_ram',
            field=models.CharField(default=1, max_length=10, verbose_name='Memoria Ram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(default=1, max_length=10, verbose_name='Processador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default=1, max_length=10, verbose_name='Armazenamento'),
            preserve_default=False,
        ),
    ]
