# Generated by Django 5.0 on 2024-11-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='imei',
            field=models.CharField(default=1, max_length=30, verbose_name='IMEI'),
            preserve_default=False,
        ),
    ]
