# Generated by Django 5.0 on 2024-11-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_phone_imei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['title'], 'verbose_name': 'Phone'},
        ),
        migrations.AddField(
            model_name='phone',
            name='is_termo_active',
            field=models.BooleanField(default=True, verbose_name='Assinado'),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_termo_inactive',
            field=models.BooleanField(default=False, verbose_name='Não assinou'),
        ),
        migrations.AddField(
            model_name='phone',
            name='last_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='phone', to='products.cooperado', verbose_name='Ultimo Usuario'),
            preserve_default=False,
        ),
    ]
