# Generated by Django 5.0 on 2024-11-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_phone_options_phone_is_termo_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='phones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='products.phone', verbose_name='Celular'),
            preserve_default=False,
        ),
    ]
