# Generated by Django 5.0 on 2024-11-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_controle_phones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperado',
            options={'ordering': ['name'], 'verbose_name': 'Funcionario'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['title'], 'verbose_name': 'Celulare'},
        ),
    ]
