# Generated by Django 5.0 on 2024-11-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cooperado_options_alter_phone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('is_termo_active', models.BooleanField(default=True, verbose_name='Assinado')),
                ('is_termo_inactive', models.BooleanField(default=False, verbose_name='Não assinou')),
                ('is_new', models.BooleanField(default=True, verbose_name='Novo')),
                ('is_used', models.BooleanField(default=True, verbose_name='Usado')),
                ('delivery', models.DateTimeField(auto_now_add=True, verbose_name='Entregue em')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Perifericos',
                'ordering': ['title'],
            },
        ),
    ]
