# Generated by Django 5.0 on 2024-11-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_perifericos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perifericos',
            name='is_termo_active',
        ),
        migrations.RemoveField(
            model_name='perifericos',
            name='is_termo_inactive',
        ),
    ]
