# Generated by Django 5.0 on 2024-11-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_perifericos_is_termo_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perifericos',
            name='amount',
            field=models.CharField(default=1, max_length=100, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
