# Generated by Django 5.0 on 2024-12-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_perifericos_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perifericos',
            options={'ordering': ['title'], 'verbose_name': 'Periferico'},
        ),
        migrations.AddField(
            model_name='controle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
