# Generated by Django 5.0 on 2024-12-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_perifericos_options_controle_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='controle',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
